export const imageCategory = [
    "Food & Drink",
    "Current Events",
    "Wallpapers",
    "3D Renders",
    "Textures & Patterns",
    "Experimental",
    "Architecture",
    "Nature",
    "Business & Work",
    "Fashion",
    "Film",
    "Health & Welness",
    "People",
    "Interiors",
    "Street Photography",
    "Animals",
    "Spirituality",
    "Travel",
    "Art & Culture",
    "History",
    "Athletics",
]